package cn.wzvtcsoft.bosdomain;

// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.timbos.ActionScript3Plugin from BosEntity

import cn.wzvtcsoft.bosdomain.persist.CoreObject;
import org.springframework.data.annotation.*;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import javax.persistence.AccessType;

@EntityListeners(AuditingEntityListener.class)
@MappedSuperclass
@Access(AccessType.FIELD)
public abstract class BosEntity extends CoreObject implements IEntity {


    /**
     * 给人识别的 Entity 的编号
     */
    @Column(length = 25)
    private String number = System.currentTimeMillis() + "";

    /**
     * 创建人的 id
     */
    @CreatedBy
    @Column(length = 25)
    private String createactorid = "";

    /**
     * 修改人的 id
     */
    @LastModifiedBy
    @Column(length = 25)
    private String updateactorid = "";

    /**
     * 最后一次的修改时间
     */
    @LastModifiedDate
    private long updatetime = 0;

    /**
     * 创建时间
     */
    @CreatedDate
    private long createtime = 0;

    //TODO 怎么设置普遍的查询时过滤掉禁用的？
    //TODO 乐观锁控制
    /**
     * 表示假删除
     */
    private boolean disabled = false;

    @Override
    public String getCreateactorid() {
        return createactorid;
    }

    public void setCreateactorid(String createactorid) {
        this.createactorid = createactorid;
    }

    @Override
    public String getUpdateactorid() {
        return updateactorid;
    }

    @Override
    public long getUpdatetime() {
        return updatetime;
    }


    public String getNumber() {
        return number;
    }

    @Override
    public long getCreatetime() {
        return createtime;
    }

    public void setUpdateactorid(String updateactorid) {
        this.updateactorid = updateactorid;
    }

    public void setUpdatetime(long updatetime) {
        this.updatetime = updatetime;
    }

    public void setCreatetime(long createtime) {
        this.createtime = createtime;
    }

    public void isAble() {
        this.disabled = true;
    }
}
